### ISSUE TITLE
why are you using Sys.printLn?????

### ISSUE THREAD

**Issue by RafPlayz69YT** [GamerPablito/GameJolt-Adaptation-for-FNF-and-Haxeflixel#3]
just use trace m8 not that hard

**Comment by GamerPablito** [comment]
Why? Any problem with that, man?

The `trace()` gives you the line you put in, but it'll also contain the ubication of the command in the file, and because this already contains a `printprefix`, using `trace()` will make the response to be written with the location, that also can be a useless thing when it also contains a text to begin with.

On the other hand, using `Sys.printLn()` will write the input line only, without any extra information, so it will contain just the info you need to know.

If you don't trust me, try it and see the difference by yourself.

**Comment by RafPlayz69YT** [comment]
why did you write a paragraph you could have just said "didnt need the location of the trace"

**Comment by GamerPablito** [comment]
Don't know, I'm just trying to be as clear as I can, you don't have to tell me what to answer, I know what to answer and the way I do

Ofc, if you don't like the way I say the things, you can just say it without being rude
